apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: modelsensitivity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: msa-frontend
          image: sensitivity.analyzer/msa-frontend
          ports:
            - containerPort: 4200