apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: modelsensitivity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo-msa
          image: sensitivity.analyzer/msa_db
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
 
  #Please let us know if the code below should be included as it is related to volume mounting yaml file.
  # volumes:
  # - name: mongodb-data
  #   persistentVolumeClaim:
  #     claimName: mongodb-pvc